// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class CogsrevNpc
{
    public string ProjectId { get; set; }

    public string Pidfull { get; set; }

    public string Nkpcode { get; set; }

    public string Description { get; set; }

    public int? Qty { get; set; }

    public string CurrCode { get; set; }

    public decimal? UnitRevenue { get; set; }

    public decimal? UnitCogs { get; set; }

    public decimal? TotalRevenue { get; set; }

    public decimal? TotalCogs { get; set; }

    public DateTime? CreatedDate { get; set; }
}