// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class CogsNpc
{
    public string ProjectId { get; set; }

    public string Pidfull { get; set; }

    public string ProjectName { get; set; }

    public string Counter { get; set; }

    public string CurrCode { get; set; }

    public string AccountName { get; set; }

    public string Saname { get; set; }

    public string Login { get; set; }

    public string Amname { get; set; }

    public string Status { get; set; }

    public string Top { get; set; }

    public string PocontractNo { get; set; }

    public DateTime? ContractDate { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreatedDate { get; set; }

    public decimal? ExRate { get; set; }

    public string CostSheetId { get; set; }

    public int? Version { get; set; }

    public int DetailId { get; set; }

    public string SubTypeCode { get; set; }

    public string SubTypeName { get; set; }

    public string Nkpcode { get; set; }

    public string Description { get; set; }

    public int? Qty { get; set; }

    public decimal? Price { get; set; }

    public int DiscUnit { get; set; }

    public decimal? Total { get; set; }
}