// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class DataBillReqNew
{
    public int Id { get; set; }

    public string ToPdescription { get; set; }

    public string Wbsid { get; set; }

    public string Milestone { get; set; }

    public double? Percentage { get; set; }

    public string Currency { get; set; }

    public double? Amount { get; set; }

    public DateTime? Bastdt { get; set; }

    public DateTime? Stbastdt { get; set; }

    public DateTime? RequestDate { get; set; }

    public DateTime? BillReqDate { get; set; }

    public string Pid { get; set; }

    public int ToppayLineId { get; set; }

    public int? BastattachId { get; set; }

    public int? StbastattachId { get; set; }

    public bool? IsDeleted { get; set; }

    public string Remark { get; set; }

    public DateTime? ReceiveDate { get; set; }

    public string ProjectIdrevenue { get; set; }

    public int? PreProcId { get; set; }

    public int? Bastid { get; set; }

    public virtual ICollection<PreProcFileAttachment> PreProcFileAttachmentBastattaches { get; set; } = new List<PreProcFileAttachment>();

    public virtual ICollection<PreProcFileAttachment> PreProcFileAttachmentStbastattaches { get; set; } = new List<PreProcFileAttachment>();
}