// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using PreProc.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace PreProc.Models
{
    public partial interface IPreProcContextProcedures
    {
        Task<List<sp_GetCustomerResult>> sp_GetCustomerAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetEmpDomainNameByNIPResult>> sp_GetEmpDomainNameByNIPAsync(string NIP, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_getEmployeeEmailByCurrentUnitResult>> sp_getEmployeeEmailByCurrentUnitAsync(string currentUnit, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetEmployeeswithParamResult>> sp_GetEmployeeswithParamAsync(string Kode, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetProjectNameByPIDResult>> sp_GetProjectNameByPIDAsync(string ID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_getProjectSupportByAMDomainResult>> sp_getProjectSupportByAMDomainAsync(string AMDomain, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_ReminderPendingBillingReason_DetailResult>> sp_ReminderPendingBillingReason_DetailAsync(string AMEmail, DateTime? ReasonDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_GetDetailIDByStockReqIDResult>> sp_StockReq_GetDetailIDByStockReqIDAsync(string StockReqID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_GetDO_DataResult>> sp_StockReq_GetDO_DataAsync(string PID, string PONumber, string NKS, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_GetIDNewResult>> sp_StockReq_GetIDNewAsync(string StockReqID, string NKS, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_GetPO_DataResult>> sp_StockReq_GetPO_DataAsync(string StockReqID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_GetPOPerStockReqResult>> sp_StockReq_GetPOPerStockReqAsync(string StockReqID, string NKS, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_GetReminderDetailResult>> sp_StockReq_GetReminderDetailAsync(string StockReqID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_IsValidToInsertDODetailResult>> sp_StockReq_IsValidToInsertDODetailAsync(int? DetailID, string NKS, int? HeaderID, string DONumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_IsValidToInsertPODetailResult>> sp_StockReq_IsValidToInsertPODetailAsync(int? HeaderID, string NKS, string PIDFull, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_IsValidToInsertPOHeaderResult>> sp_StockReq_IsValidToInsertPOHeaderAsync(int? DetailID, int? PONumber, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_IsValidToInsertStockReqResult>> sp_StockReq_IsValidToInsertStockReqAsync(string StockReqID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_IsValidToInsertStockReqDetailResult>> sp_StockReq_IsValidToInsertStockReqDetailAsync(string ST_ID, string NKS, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_StockReq_PODetailsByStockReqIDResult>> sp_StockReq_PODetailsByStockReqIDAsync(string StockReqID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
