// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MasterListPreProcReminder
{
    public int Id { get; set; }

    public string ReminderName { get; set; }

    public int ReminderDuration { get; set; }

    public int? ReminderEscalationDuration { get; set; }

    public int? ReminderEscalation1Count { get; set; }

    public int? ReminderEscalation2Count { get; set; }
}