// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MlpPoAllOracle
{
    public string NoPo { get; set; }

    public DateTime? TanggalPo { get; set; }

    public string NamaVendor { get; set; }

    public string AddressLine1 { get; set; }

    public string AddressLine2 { get; set; }

    public string AddressLine3 { get; set; }

    public string AddressLine4 { get; set; }

    public string City { get; set; }

    public string PostalCode { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string NoVendor { get; set; }

    public string Pid { get; set; }

    public string Buyer { get; set; }

    public string Term { get; set; }

    public DateTime? DueDate { get; set; }

    public string ItemNo { get; set; }

    public string Description { get; set; }

    public string VendorCatalog { get; set; }

    public string Quantity { get; set; }

    public string Uom { get; set; }

    public string UnitPrice { get; set; }

    public string CurrencyCode { get; set; }
}