// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MlptStockreqPoAll
{
    public string StockReqNumber { get; set; }

    public string PidSo { get; set; }

    public string PoNumber { get; set; }

    public DateTime? PoDate { get; set; }

    public string VendorName { get; set; }

    public string VendorNo { get; set; }

    public string Buyer { get; set; }

    public string Term { get; set; }

    public DateTime? DueDate { get; set; }

    public string ItemNo { get; set; }

    public string ItemDescription { get; set; }

    public string VendorCatalog { get; set; }

    public decimal? PoQuantity { get; set; }

    public string Uom { get; set; }

    public decimal? PoUnitPrice { get; set; }

    public string CurrencyCode { get; set; }
}