// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MlptStockreqPoDoV
{
    public string StockReqNumber { get; set; }

    public string Requestor { get; set; }

    public string PoNumber { get; set; }

    public DateTime? PoDate { get; set; }

    public string Nks { get; set; }

    public string ItemDescription { get; set; }

    public int? PoQuantity { get; set; }

    public int? QtyGrnRma { get; set; }

    public string CurrencyCode { get; set; }

    public decimal? PoUnitPrice { get; set; }

    public decimal? Amount { get; set; }

    public string PidSoRma { get; set; }

    public string DoNumber { get; set; }

    public DateTime? DoRmaDate { get; set; }

    public string LotNumber { get; set; }

    public int? OrgId { get; set; }

    public int? DoQty { get; set; }

    public DateTime? GrDate { get; set; }
}