// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsCommentType
{
    public int Id { get; set; }

    public string Type { get; set; }

    public virtual ICollection<PreProcApprovalHistory> PreProcApprovalHistories { get; set; } = new List<PreProcApprovalHistory>();
}