// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsContingencyCost
{
    public bool? Type { get; set; }

    public string Text { get; set; }

    public int Id { get; set; }
}