// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsCustomerVw
{
    public int MsAccountId { get; set; }

    public string AccountId { get; set; }

    public string AccountName { get; set; }

    public string InitialCode { get; set; }

    public string FgActive { get; set; }

    public DateTime? Created { get; set; }

    public DateTime? Modified { get; set; }
}