// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsDocType
{
    public int Id { get; set; }

    public string DocType { get; set; }

    public string Desc { get; set; }

    public virtual ICollection<PreProcFileAttachment> PreProcFileAttachments { get; set; } = new List<PreProcFileAttachment>();

    public virtual ICollection<PreProcHeaderAttachment> PreProcHeaderAttachments { get; set; } = new List<PreProcHeaderAttachment>();
}