// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsNkproduct
{
    public string NkpcodeLinkTitle { get; set; }

    public string Nkpname { get; set; }

    public string VendorId { get; set; }

    public string TypeCode { get; set; }

    public string ProductManager { get; set; }

    public string Domain { get; set; }

    public string TeamService { get; set; }

    public string TeamServiceUnitShortName { get; set; }

    public string Avtive { get; set; }

    public string NkpcodeTitle { get; set; }

    public string NkpcodeLinkTitleNoMenu { get; set; }

    public DateTime? Created { get; set; }

    public DateTime? Modified { get; set; }
}