// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsParameterValue
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Parameter { get; set; }

    public string AlphaNumericValue { get; set; }

    public decimal? NumericValue { get; set; }

    public string Description { get; set; }

    public int? Level { get; set; }
}