// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsPrincipalPreload
{
    public int Id { get; set; }

    public string Type { get; set; }

    public virtual ICollection<PreProcPrincipalProjectRevenue> PreProcPrincipalProjectRevenues { get; set; } = new List<PreProcPrincipalProjectRevenue>();
}