// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsPresalesId
{
    public int Id { get; set; }

    public string PresalesId { get; set; }
}