// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class MsVendor
{
    public string VendorName { get; set; }

    public string VendorTypeLookupCode { get; set; }
}