// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcClarification
{
    public int Id { get; set; }

    public int? PreProcId { get; set; }

    public string Response { get; set; }

    public string MailTo { get; set; }

    public string UserNameMailTo { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public string ClarAttachment { get; set; }

    public virtual PreProcGeneralInfo2 PreProc { get; set; }

    public virtual ICollection<PreProcClarificationAttachment> PreProcClarificationAttachments { get; set; } = new List<PreProcClarificationAttachment>();
}