// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcSession
{
    public string PreProcid { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? Modified { get; set; }
}