// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcClarificationAttachment
{
    public int PreProcId { get; set; }

    public int Id { get; set; }

    public string FileName { get; set; }

    public int? ClarificationId { get; set; }

    public string InitialFileName { get; set; }

    public virtual PreProcClarification Clarification { get; set; }

    public virtual PreProcGeneralInfo2 PreProc { get; set; }
}