// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcHistoryReminder
{
    public int Id { get; set; }

    public int ReminderId { get; set; }

    public int PreProcId { get; set; }

    public DateTime FirstReminderDate { get; set; }

    public DateTime LastReminderDate { get; set; }

    public int EscalationCount { get; set; }

    public string ReminderPic { get; set; }
}