// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcFieldExcel
{
    public int? Id { get; set; }
    public string Principle { get; set; }
    public string ItemDesc { get; set; }
    public bool? SurDuk { get; set; }
    public double? Qty { get; set; }
    public string Nkpcode { get; set; }
    public int? Warranty { get; set; }
    public bool? Insurance { get; set; }

}