// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcReminder
{
    public int Id { get; set; }

    public int? PreProcId { get; set; }

    public string Reminder { get; set; }

    public string MailTo { get; set; }

    public string UsernameMailTo { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public virtual PreProcGeneralInfo2 PreProc { get; set; }
}