// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcGeneralInfo2
{
    public int Id { get; set; }

    public int ListItemId { get; set; }

    public string PresalesId { get; set; }

    public string RfpId { get; set; }

    public string ProposalId { get; set; }

    public string QuotationId { get; set; }

    public string Description { get; set; }

    public string Customer { get; set; }

    public decimal? ProjectValueIdr { get; set; }

    public string Pid { get; set; }

    public string ProjectSupport { get; set; }

    public string Pm { get; set; }

    public string Pc { get; set; }

    public string Stage { get; set; }

    public string PropMgr { get; set; }

    public string TenderAdm { get; set; }

    public string PicProc { get; set; }

    public string Am { get; set; }

    public decimal? ProjectValueUsd { get; set; }

    public DateTime? CreationDate { get; set; }

    public string TitleLinkTitle { get; set; }

    public string TitleTitle { get; set; }

    public string ContentType { get; set; }

    public DateTime? Modified { get; set; }

    public DateTime? Created { get; set; }

    public string CreatedBy { get; set; }

    public string ModifiedBy { get; set; }

    public string Version { get; set; }

    public bool? Attachments { get; set; }

    public string Edit { get; set; }

    public string TitleLinkTitleNoMenu { get; set; }

    public string Type { get; set; }

    public string ItemChildCount { get; set; }

    public string FolderChildCount { get; set; }

    public string AppCreatedBy { get; set; }

    public string AppModifiedBy { get; set; }

    public string ProjectType { get; set; }

    public DateTime? ProposalSubmissionDate { get; set; }

    public DateTime? QuotationDeadline { get; set; }

    public bool? Hedging { get; set; }

    public string CustomerCode { get; set; }

    public string OverallRisk { get; set; }

    public string OpportunityId { get; set; }

    public double? TotalCogsidr { get; set; }

    public double? TotalCogsusd { get; set; }

    public double? TotalPriceIdr { get; set; }

    public double? TotalPriceUsd { get; set; }

    public bool? InitialRiskReview { get; set; }

    public bool? OptyStatus { get; set; }

    public decimal? EstGpgeneral { get; set; }

    public string EmailCommitteeDefault { get; set; }

    public string Cvpm { get; set; }

    public string Cvpc { get; set; }

    public string PreId { get; set; }

    public bool? NeedWarranty { get; set; }

    public bool? IsComplete { get; set; }

    public virtual ICollection<PreProcClarificationAttachment> PreProcClarificationAttachments { get; set; } = new List<PreProcClarificationAttachment>();

    public virtual ICollection<PreProcClarification> PreProcClarifications { get; set; } = new List<PreProcClarification>();

    public virtual ICollection<PreProcDetail> PreProcDetails { get; set; } = new List<PreProcDetail>();

    public virtual ICollection<PreProcHeaderAttachment> PreProcHeaderAttachments { get; set; } = new List<PreProcHeaderAttachment>();

    public virtual ICollection<PreProcPmochecklist> PreProcPmochecklists { get; set; } = new List<PreProcPmochecklist>();

    public virtual ICollection<PreProcReminder> PreProcReminders { get; set; } = new List<PreProcReminder>();

    public virtual ICollection<PreProcRiskAssesmentDatum> PreProcRiskAssesmentData { get; set; } = new List<PreProcRiskAssesmentDatum>();

    public virtual ICollection<PreProcRiskDatum> PreProcRiskData { get; set; } = new List<PreProcRiskDatum>();
}