// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcPendingBillingReason
{
    public int Id { get; set; }

    public int PreProcId { get; set; }

    public bool NeedEscalation { get; set; }

    public int? EscalationReasonId { get; set; }

    public string OtherReason { get; set; }

    public DateTime? ReasonCreatedDate { get; set; }

    public DateTime? ReasonUpdateDate { get; set; }

    public string ReasonPic { get; set; }
}