// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcHeaderAttachment
{
    public int Id { get; set; }

    public string Folder { get; set; }

    public string FileName { get; set; }

    public int PreProcId { get; set; }

    public string StrictedFileName { get; set; }

    public string ModifiedBy { get; set; }

    public int? DocumentTypeId { get; set; }

    public bool? HasBeenUploaded { get; set; }

    public int? ItemId { get; set; }

    public string UploadedFrom { get; set; }

    public virtual MsDocType DocumentType { get; set; }

    public virtual PreProcGeneralInfo2 PreProc { get; set; }
}