// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcAuditTrail
{
    public string NameField { get; set; }

    public string ValueBefore { get; set; }

    public string ValueAfter { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime? ModifiedTime { get; set; }

    public string Pcname { get; set; }

    public int Id { get; set; }

    public int? PreProcId { get; set; }
}