// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcRisk
{
    public int RiskId { get; set; }

    public string RiskName { get; set; }

    public int? RiskWeight { get; set; }

    public bool? IsActive { get; set; }

    public int? RiskOrderNo { get; set; }

    public string RiskType { get; set; }
}