// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcRiskAssesmentDatum
{
    public int Id { get; set; }

    public int? PreProcId { get; set; }

    public string Description { get; set; }

    public DateTime? ReviewDate { get; set; }

    public string SourceBudget { get; set; }

    public DateTime? EstProjectStart { get; set; }

    public decimal? EstMtac { get; set; }

    public DateTime? EstProjectCompletion { get; set; }

    public string ProcurementType { get; set; }

    public string Competition { get; set; }

    public string ProjectSource { get; set; }

    public string Competitor { get; set; }

    public decimal? ContigencyCost { get; set; }

    public string PredefinedConditionReqByPrincipal { get; set; }

    public string ProjectCondition { get; set; }

    public bool? AmapprovalOutcome { get; set; }

    public bool? CeapprovalOutcome { get; set; }

    public bool? SdapprovalOutcome { get; set; }

    public string EmailAssignTo { get; set; }

    public int? AuditTempId { get; set; }

    public bool? IsAssessmentStarted { get; set; }

    public virtual PreProcGeneralInfo2 PreProc { get; set; }
}