// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcApprovalHistory
{
    public int Id { get; set; }

    public int? PreProcId { get; set; }

    public string ApproverName { get; set; }

    public string ApproverRole { get; set; }

    public DateTime? ApprovalDate { get; set; }

    public string Status { get; set; }

    public string Remark { get; set; }

    public int? DetailId { get; set; }

    public int? Type { get; set; }

    public string DomainName { get; set; }

    public virtual MsCommentType TypeNavigation { get; set; }
}