// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcRiskDatum
{
    public int Id { get; set; }

    public int PreProcId { get; set; }

    public int RiskOrder { get; set; }

    public string CheckedBy { get; set; }

    public string RiskType { get; set; }

    public int? RiskId { get; set; }

    public virtual PreProcGeneralInfo2 PreProc { get; set; }
}