// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcPmochecklist
{
    public int Id { get; set; }

    public int? PreProcId { get; set; }

    public string CustomerPic { get; set; }

    public string HighLevelSow { get; set; }

    public string ProjectSite { get; set; }

    public string ProjectValue { get; set; }

    public DateTime? EstimatedStartDate { get; set; }

    public DateTime? EstimatedKickOffDate { get; set; }

    public string EstimatedKickOffNote { get; set; }

    public DateTime? EndDate { get; set; }

    public string PicWarranty { get; set; }

    public string ProductTeamPic { get; set; }

    public string SpecificTerms { get; set; }

    public decimal? Pmvalue { get; set; }

    public int? Pmmandays { get; set; }

    public decimal? Pcvalue { get; set; }

    public int? Pcmandays { get; set; }

    public bool? CheckedCustomerPic { get; set; }

    public bool? CheckedHighLevelSow { get; set; }

    public bool? CheckedProjectSite { get; set; }

    public bool? CheckedProjectValue { get; set; }

    public bool? CheckedEstimatedStartEndDate { get; set; }

    public bool? CheckedEstimatedKickOff { get; set; }

    public bool? CheckedPicwarrantyTeam { get; set; }

    public bool? CheckedProductTeamPic { get; set; }

    public bool? CheckedSpkorPoorContract { get; set; }

    public bool? CheckedRfporRksorTor { get; set; }

    public bool? CheckedQuotation { get; set; }

    public bool? CheckedProposal { get; set; }

    public bool? CheckedBoQ { get; set; }

    public bool? CheckedNegotiationMoM { get; set; }

    public bool? CheckedOtherAttachment { get; set; }

    public bool? CheckedPmcostAttachment { get; set; }

    public virtual PreProcGeneralInfo2 PreProc { get; set; }
}