// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcPrincipalProjectRevenue
{
    public int Id { get; set; }

    public int? PreProcId { get; set; }

    public string PrincipalName { get; set; }

    public decimal? ProjectRevenue { get; set; }

    public string PrincipalScope { get; set; }

    public int? Preload { get; set; }

    public int? AuditDetailId { get; set; }

    public virtual MsPrincipalPreload PreloadNavigation { get; set; }
}