// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcPodatum
{
    public int Id { get; set; }

    public int DetailId { get; set; }

    public int PreProcId { get; set; }

    public int? Poid { get; set; }

    public DateTime? Podate { get; set; }

    public string PolineId { get; set; }

    public DateTime? ExpectedPoissuedDate { get; set; }

    public DateTime? Etd { get; set; }

    public DateTime? Eta { get; set; }

    public DateTime? Grdate { get; set; }

    public int? Grqty { get; set; }

    public int? Grbacklog { get; set; }

    public int? Poqty { get; set; }

    public string Idnew { get; set; }

    public string VendorName { get; set; }

    public string Buyer { get; set; }

    public string Term { get; set; }

    public string ItemDescription { get; set; }

    public string ItemNo { get; set; }

    public string Curr { get; set; }

    public decimal? UnitPrice { get; set; }

    public string Uom { get; set; }

    public string VendorCatalog { get; set; }
}