// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class PreProcFileAttachment
{
    public int Id { get; set; }

    public string Folder { get; set; }

    public string FileName { get; set; }

    public int PreProcId { get; set; }

    public string StrictedFileName { get; set; }

    public string ModifiedBy { get; set; }

    public int? DocumentTypeId { get; set; }

    public bool? HasBeenUploaded { get; set; }

    public int? SpecAttachId { get; set; }

    public int? SurdukAttachId { get; set; }

    public int? VendorQuoAttachId { get; set; }

    public int? MpoattachId { get; set; }

    public int? BastattachId { get; set; }

    public int? StbastattachId { get; set; }

    public int? GrnattachId { get; set; }

    public bool? TriggerMaintenance { get; set; }

    public int? Bastid { get; set; }

    public virtual DataBillReqNew Bastattach { get; set; }

    public virtual MsDocType DocumentType { get; set; }

    public virtual PreProcDetail Grnattach { get; set; }

    public virtual PreProcDetail Mpoattach { get; set; }

    public virtual PreProcDetail SpecAttach { get; set; }

    public virtual DataBillReqNew Stbastattach { get; set; }

    public virtual PreProcDetail SurdukAttach { get; set; }

    public virtual PreProcDetail VendorQuoAttach { get; set; }
}