// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PreProc.Models
{
    public partial class sp_GetProjectNameByPIDResult
    {
        public int ListItemID { get; set; }
        public string PID { get; set; }
        public string Description { get; set; }
    }
}
