// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PreProc.Models
{
    public partial class sp_GetCustomerResult
    {
        public int msAccount_ID { get; set; }
        public string AccountID { get; set; }
        public string AccountName { get; set; }
        public string InitialCode { get; set; }
        public string FgActive { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}
