// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PreProc.Models
{
    public partial class sp_getProjectSupportByAMDomainResult
    {
        public string AMDept { get; set; }
        public string ProjectSupport { get; set; }
    }
}
