// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PreProc.Models
{
    public partial class sp_GetEmployeeswithParamResult
    {
        public int? msEmployees_ID { get; set; }
        [Column("NIP", TypeName = "decimal(15,5)")]
        public decimal NIP { get; set; }
        public string NAME { get; set; }
        public string CurrentGroup { get; set; }
        public string Employee_Email { get; set; }
        public string DomainName { get; set; }
        public string IsManager { get; set; }
        public int? isPCAuthorize { get; set; }
        public int? IsActive { get; set; }
        public int? ActingName { get; set; }
        public DateTime? Created { get; set; }
        public DateTime? Modified { get; set; }
    }
}
