// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PreProc.Models
{
    public partial class sp_ReminderPendingBillingReason_DetailResult
    {
        public string PID { get; set; }
        public string ProjectName { get; set; }
        public string IssueDescription { get; set; }
        public string AM { get; set; }
        public DateTime? ReasonDate { get; set; }
        public DateTime? LastReminderDate { get; set; }
        public int? EscalationCount { get; set; }
        public int? PreProciD { get; set; }
    }
}
