// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PreProc.Models
{
    public partial class sp_StockReq_PODetailsByStockReqIDResult
    {
        public string STOCK_REQ_NUMBER { get; set; }
        public string REQUESTOR { get; set; }
        public string NKS { get; set; }
        public string ITEM_DESCRIPTION { get; set; }
        public int? Total_PO_Qty { get; set; }
        public string CURRENCY_CODE { get; set; }
        [Column("PO_UNIT_PRICE", TypeName = "decimal(18,2)")]
        public decimal? PO_UNIT_PRICE { get; set; }
    }
}
