// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PreProc.Models
{
    public partial class sp_StockReq_GetIDNewResult
    {
        public string PIDFull { get; set; }
        public string NKPCode { get; set; }
        public string ItemDesc { get; set; }
        public string IDNew { get; set; }
        public string Currency { get; set; }
    }
}
