// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PreProc.Models
{
    public partial class sp_StockReq_IsValidToInsertPODetailResult
    {
        public bool? ValidToInsert { get; set; }
        public int? countDetailPO { get; set; }
    }
}
