// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class StockRequisitionMonitoring
{
    public int Id { get; set; }

    public string Am { get; set; }

    public string ProjectSupport { get; set; }

    public string Procurement { get; set; }

    public string Warehouse { get; set; }

    public string Pmomanager { get; set; }

    public string SystemAdmin { get; set; }

    public string ProjectedCustomer { get; set; }

    public string Description { get; set; }

    public string Title { get; set; }

    public DateTime? Created { get; set; }
}