// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class StockReqItemNewReminderHistory
{
    public string StockreqId { get; set; }

    public DateTime? LastReminderDate { get; set; }
}