// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class TempPreProcDetail
{
    public int? Id { get; set; }

    public int DetailId { get; set; }

    public string Principle { get; set; }

    public string ItemDesc { get; set; }

    public string Spec { get; set; }

    public bool? SurDukCheck { get; set; }

    public string SurDuk { get; set; }

    public double? Qty { get; set; }

    public string Currency { get; set; }

    public double? UnitCogs { get; set; }

    public double? UnitPrice { get; set; }

    public string TotalCogs { get; set; }

    public string TotalPrice { get; set; }

    public string Vendor { get; set; }

    public string VendorQuotation { get; set; }

    public DateTime? ExpectedPoissuedDate { get; set; }

    public DateTime? Etd { get; set; }

    public string Mlptpono { get; set; }

    public DateTime? Mlptpodate { get; set; }

    public string Mlptpo { get; set; }

    public DateTime? Eta { get; set; }

    public DateTime? Grdate { get; set; }

    public double? Grqty { get; set; }

    public double? Grbacklog { get; set; }

    public string PresalesReview { get; set; }

    public string AmmanagerApproval { get; set; }

    public string RemarkOnItem { get; set; }

    public bool? ProcessedPresalesReview { get; set; }

    public bool? ProcessedAmreview { get; set; }

    public string PonumberId { get; set; }

    public string Nkpcode { get; set; }

    public string ProductManager { get; set; }

    public int? Warranty { get; set; }

    public bool? Insurance { get; set; }

    public int? SpecAttachId { get; set; }

    public int? SurdukAttachId { get; set; }

    public int? VendorQuoAttachId { get; set; }

    public int? MpoattachId { get; set; }

    public string Risk { get; set; }

    public int? AuditDetailId { get; set; }

    public string PreProcId { get; set; }

    public string Idnew { get; set; }

    public int? GrnattachId { get; set; }

    public string Grn { get; set; }

    public string Pidfull { get; set; }

    public int? FirstId { get; set; }

    public int? SecondId { get; set; }

    public int? DetailIdold { get; set; }
}