// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwCshdEpm
{
    public string CostSheetId { get; set; }

    public decimal? Total { get; set; }

    public string MpcPid { get; set; }

    public string MpcName { get; set; }

    public string MpcDescription { get; set; }

    public DateTime? MpcPlannedstartdate { get; set; }

    public DateTime? MpcPlannedenddate { get; set; }

    public string Owneridname { get; set; }

    public string MpcStatus { get; set; }

    public string MpcCategory { get; set; }

    public string DomainName { get; set; }

    public string CurrCode { get; set; }

    public decimal? Exrate { get; set; }

    public decimal? TotalRevenue { get; set; }

    public string AuthorizedGroup { get; set; }

    public int? Version { get; set; }

    public string PocontractNo { get; set; }

    public DateTime? ContractDate { get; set; }

    public string Amname { get; set; }

    public string Saname { get; set; }

    public string TermOfPayment { get; set; }

    public string Amlogin { get; set; }

    public string Salogin { get; set; }

    public string AccountName { get; set; }

    public string ProjectId { get; set; }

    public string Counter { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ApprovalDate { get; set; }
}