// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwDataInvoice
{
    public string Pid { get; set; }

    public decimal? TotalRevenue { get; set; }

    public string CurrCode { get; set; }

    public decimal JumlahInvoice { get; set; }
}