// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwEmployeeBaseEreq
{
    public decimal Nip { get; set; }

    public string Nama { get; set; }

    public string Level00 { get; set; }

    public string Level01 { get; set; }

    public string Level02 { get; set; }

    public string Level03 { get; set; }

    public string Bu { get; set; }

    public string Level04 { get; set; }

    public string Division { get; set; }

    public string Level05 { get; set; }

    public string Department { get; set; }

    public int? Secretary { get; set; }

    public string Status { get; set; }

    public int? Level { get; set; }

    public string CurrentGroup { get; set; }

    public int? ActiveStatus { get; set; }

    public int? StatusEmployee { get; set; }

    public string Login { get; set; }

    public string EmailAddress { get; set; }

    public string Level06 { get; set; }

    public string Section { get; set; }

    public string Company { get; set; }

    public int Id { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime ModifiedDate { get; set; }

    public string Level07 { get; set; }

    public decimal? ActiveNip { get; set; }
}