// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwExportItem
{
    public int? Id { get; set; }

    public int ListItemId { get; set; }

    public string DetailId { get; set; }

    public string Principle { get; set; }

    public string Nkpcode { get; set; }

    public string ItemDesc { get; set; }

    public double? Qty { get; set; }

    public int? Warranty { get; set; }

    public string SurDuk { get; set; }

    public string Insurance { get; set; }
}