// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwGetAllPid
{
    public int TrProjectIdId { get; set; }

    public string ProjectId { get; set; }

    public string ProjectName { get; set; }

    public string Description { get; set; }

    public string OwnershipCode { get; set; }

    public int? OwnershipCodeId { get; set; }

    public int? Year { get; set; }

    public DateTime? Start { get; set; }

    public DateTime? End { get; set; }

    public string ProjectTypeId { get; set; }

    public int? ProjectTypeIdId { get; set; }

    public string CurrencyId { get; set; }

    public int? CurrencyIdId { get; set; }

    public decimal? ProjectRevenue { get; set; }

    public string TreasurySpotRate { get; set; }

    public int? BrId { get; set; }

    public string Br { get; set; }

    public string CustomerId { get; set; }

    public int? CustomerIdId { get; set; }

    public string EndCustomerId { get; set; }

    public int? EndCustomerIdId { get; set; }

    public string FirstBr { get; set; }

    public int? FirstBrId { get; set; }

    public decimal? SpecialRate { get; set; }

    public decimal? ProjectCogs { get; set; }

    public string CurrencyCogs { get; set; }

    public int? CurrencyCogsId { get; set; }

    public string CustomerCode { get; set; }

    public decimal? ExchangeRate { get; set; }

    public int? ExchangeRateId { get; set; }

    public string HedgingStatus { get; set; }

    public string Pidcategory { get; set; }

    public int? PidcategoryId { get; set; }

    public string ProjectStatus { get; set; }

    public int? ProjectStatusId { get; set; }

    public decimal? ProjectRevenueIdr { get; set; }

    public string Creator { get; set; }

    public int? CreatorId { get; set; }

    public decimal? ProjectCogsbefore { get; set; }

    public decimal? SpecialRateBefore { get; set; }

    public string RemarkForEdit { get; set; }

    public string CurrencyIdbefore { get; set; }

    public int? CurrencyIdbeforeId { get; set; }

    public string CurrencyCogsbefore { get; set; }

    public int? CurrencyCogsbeforeId { get; set; }

    public int? IsEdited { get; set; }

    public string FlagCurrency { get; set; }

    public DateTime? Created { get; set; }

    public DateTime? Modified { get; set; }

    public int? FlagHasCostsheet { get; set; }
}