// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwGetMplPoAll
{
    public string Pidnum { get; set; }

    public string Pid { get; set; }

    public string NoPo { get; set; }

    public DateTime? TanggalPo { get; set; }

    public string NamaVendor { get; set; }

    public string NoVendor { get; set; }

    public string Buyer { get; set; }

    public string Term { get; set; }

    public DateTime? DueDate { get; set; }

    public string ItemNo { get; set; }

    public string Description { get; set; }

    public string VendorCatalog { get; set; }

    public string Quantity { get; set; }

    public string Uom { get; set; }

    public string UnitPrice { get; set; }

    public string CurrencyCode { get; set; }
}