// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwGetAllOptyId
{
    public int Id { get; set; }

    public string Opportunityid { get; set; }

    public string Name { get; set; }

    public string InitialCode { get; set; }

    public string AccountName { get; set; }

    public DateTime? Estimatedclosedate { get; set; }

    public decimal? Estimatedvalue { get; set; }

    public decimal? NewPercentgp { get; set; }

    public decimal? NewEstimatedgp { get; set; }

    public string Opportunityratingcode { get; set; }

    public string NewDealregistration { get; set; }

    public string Ownerid { get; set; }

    public decimal? NewPercentdp { get; set; }

    public string Budgetstatus { get; set; }

    public decimal? NewDownpayment { get; set; }

    public DateTime? NewEstdpreceivedate { get; set; }

    public string NewOptynumber { get; set; }

    public string NewPresalesid { get; set; }

    public decimal? NewProductrevenue { get; set; }

    public string NewRecurring { get; set; }

    public decimal? Totalamount { get; set; }

    public DateTime? Modifiedon { get; set; }

    public string Statecode { get; set; }

    public string Currency { get; set; }

    public string Internalemailaddress { get; set; }
}