// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwGetNkpname
{
    public string Nkpname { get; set; }

    public string NkpcodeLinkTitle { get; set; }

    public string VendorId { get; set; }

    public string ProductManager { get; set; }

    public string Domain { get; set; }
}