// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwGetPmmemberFull
{
    public Guid SystemUserId { get; set; }

    public string EmployeeName { get; set; }

    public string FullName { get; set; }

    public bool? LeaveStatus { get; set; }

    public string Manager1Name { get; set; }

    public string Manager2Name { get; set; }

    public string Manager3Name { get; set; }

    public string Manager4Name { get; set; }

    public string Manager5Name { get; set; }

    public string EmployeeEmail { get; set; }

    public string Manager1Email { get; set; }

    public string Manager2Email { get; set; }

    public string Manager3Email { get; set; }

    public string Manager4Email { get; set; }

    public string Manager5Email { get; set; }

    public string BankAccountNumber { get; set; }

    public string EmployeeNip { get; set; }

    public string MobilePhone { get; set; }

    public string Group { get; set; }

    public string Department { get; set; }

    public string Directorat { get; set; }

    public string Section { get; set; }

    public string Division { get; set; }

    public string Unit { get; set; }

    public string JobTitle { get; set; }

    public string DomainName { get; set; }

    public bool? NeedActing { get; set; }

    public string EmployeeSystemName { get; set; }

    public string JobTitleLevel { get; set; }

    public string CurrentUnit { get; set; }
}