// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwGpTrStockReqForm
{
    public string StockReqId { get; set; }

    public string ProjectId { get; set; }

    public string QuotationNo { get; set; }

    public string ProposalNo { get; set; }

    public string Currency { get; set; }

    public decimal ReqNip { get; set; }

    public string ReqName { get; set; }

    public DateTime ReqArrivalDate { get; set; }

    public string ProjectDesc { get; set; }

    public string CustomerType { get; set; }

    public string ProjectedCust { get; set; }

    public double ProjectedGrossProfit { get; set; }

    public DateTime ContractReceived { get; set; }

    public string Remark { get; set; }

    public DateTime RequestedDate { get; set; }

    public string ReqAppStatus { get; set; }

    public string Pid { get; set; }

    public string VendorName { get; set; }
}