// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwIssuePendingBillingReason
{
    public string StatusPending { get; set; }

    public string FullPid { get; set; }

    public string IssueTypeFrom { get; set; }

    public string IssueDescription { get; set; }

    public string ReasonPic { get; set; }

    public string PmloginInPreProc { get; set; }

    public string PmnameInPreProc { get; set; }

    public string PcloginInPreProc { get; set; }

    public string PcnameInPreProc { get; set; }

    public DateTime? ReasonDate { get; set; }

    public DateTime? ReasonCreatedDate { get; set; }

    public DateTime? ReasonUpdateDate { get; set; }
}