// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwKodeAccount
{
    public string Name { get; set; }

    public string NewInitialCodeNew { get; set; }

    public int Accountclassificationcode { get; set; }

    public int Statecode { get; set; }

    public string Kodeacc { get; set; }
}