// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwMappingSagroup
{
    public int MsOrgId { get; set; }

    public int MsEmployeesId { get; set; }

    public string UnitShortName { get; set; }

    public string DomainName { get; set; }
}