// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwReasonPicname
{
    public int ReasonId { get; set; }

    public string Pic { get; set; }

    public string Picname { get; set; }
}