// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwReminderPendingBillingReasonHeader
{
    public string Am { get; set; }

    public DateTime? ReasonDate { get; set; }
}