// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwReportTrackingDeliverySheet
{
    public int Id { get; set; }

    public string ProjectName { get; set; }

    public string Pid { get; set; }

    public string PocontractNo { get; set; }

    public string Customer { get; set; }

    public int ListItemId { get; set; }

    public string Idnew { get; set; }

    public string ItemDesc { get; set; }

    public string RemarkOnItem { get; set; }

    public string Mlptpono { get; set; }

    public DateTime? Mlptpodate { get; set; }

    public double? Qty { get; set; }

    public DateTime? Eta { get; set; }

    public DateTime? Etd { get; set; }

    public DateTime? Grdate { get; set; }

    public double Grqty { get; set; }
}