// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwReminderNewStockReq
{
    public int Id { get; set; }

    public int ListItemId { get; set; }

    public string Pid { get; set; }

    public string ProjectSupport { get; set; }

    public string Am { get; set; }

    public string Warehouse { get; set; }

    public string Psmanager { get; set; }
}