// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwStockReqReminderGrheader
{
    public string Pid { get; set; }

    public string Description { get; set; }

    public string Am { get; set; }

    public string ProjectSupport { get; set; }

    public int ListItemId { get; set; }

    public int PreProcId { get; set; }

    public string PsMgr { get; set; }
}