// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PreProc.Models;

public partial class VwStockReqReminder
{
    public int? Listitemid { get; set; }

    public string StockReqNumber { get; set; }

    public DateTime? GrDate { get; set; }

    public string Requestor { get; set; }

    public string Am { get; set; }

    public string ProjectSupport { get; set; }

    public string PsMgr { get; set; }
}